name: ci/cd workflow
 
on:
  push:
    branches:
     - master
     - dev
  pull_request:
 
jobs:
 tests-laravel:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       php: [8.0.0, 8.0.2]
 
   name: Prueba - PHP ${{ matrix.php }}
 
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
     - name: Cache PHP dependencies
       uses: actions/cache@v1
       with:
         path: vendor
         key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
 
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
         php-version: ${{ matrix.php }}
         extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
         coverage: none
 
     - name: Copy ENV Laravel Configuration for CI
       run: php -r "file_exists('.env') || copy('.env.example', '.env');"
 
     - name: Install dependencies
       run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
 
     - name: Generate key
       run: php artisan key:generate
 
     - name: Execute tests
       run: vendor/bin/phpunit --verbose
 
 deploy:
   runs-on: ubuntu-latest
   needs: tests-laravel
   if: github.ref == 'refs/heads/master'
   services:
    mysql:
     image: mysql:5.7
     env:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE:  laravel_test
     ports:
      - 33306:3306
     options: >-
     --health-cmd="mysqladmin ping"
     --health-interval=10s
     --health-timeout=5s
     --health-retries=3

   steps:
     - name: Checkout code
       uses: actions/checkout@v2
 
     - name: Cache PHP dependencies
       uses: actions/cache@v1
       with:
         path: vendor
         key: dependencies-php-composer-${{ hashFiles('**/composer.lock') }}
 
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
         php-version: 8.0
         extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd
         coverage: none
 
     - name: Install dependencies
       run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
 
     - name: Copy dotenv file
       run: php -r "file_put_contents(__DIR__ . '/.env', '${{ secrets.DOT_ENV }}');"
 
     - name: Deploy
       uses: appleboy/scp-action@master
       env:
         HOST: ${{ secrets.SSH_HOST }}
         KEY: ${{ secrets.SSH_KEY }}
         USERNAME: ${{ secrets.SSH_USERNAME }}         
       with: 
         source: "."
         target: "/var/www/html"
         strip_components: 1

     - name: Generate Key
       run: php artisan key:generate

     - name: Directory Permissions
       run: chmod -R 777 storage bootstrap/cache

     - name: Run migrations
       env: 
        DB_CONNECTION: mysql
        DB_DATABASE: laravel_test
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
       run: |
        php artisan migrate
        php artisan config:clear
        php artisan route:clear
        php artisan cache:clear
        
        
        
        